"""
Imitator API
Copy this file to your workspace and import it to start writing plugins
"""
from typing import Callable, Any, Literal

Wrapped = Callable

class NextType:
    def __call__(self, state: dict): ...

class TermIO:
    @staticmethod
    def getch() -> str | None: ...
    @staticmethod
    def puts(string: str) -> None: ...
    @staticmethod
    def flush() -> None: ...

StateType = dict[str, Any]

HookAction = Literal[
    "before", "instead", "after", "init", "on_end",
    "on_full_end", "on_start", "on_interrupt_occur"
]

def hook(action: HookAction) -> Wrapped: ...
def add_hook(action: HookAction, hook: Callable[NextType, dict[str, Any]]) -> None: ...
def safe_open(path: str) -> str: ...
def jput(char: str) -> None: ...
def jprint(string: str) -> None: ...
def load_hook_from_file(path: str) -> None: ...
def add_metadata(metadata: dict[str, str]) -> None: ...
def set_non_blocking_io() -> None: ...
def set_blocking_io() -> None: ...
