"""
Imitator API
Copy this file to your workspace and import it to start writing plugins
"""
from typing import Callable, Any

Wrapped = Callable

class NextType: ...

class TermIO:
    @staticmethod
    def getch() -> str | None: ...
    @staticmethod
    def puts(string: str) -> None: ...
    @staticmethod
    def flush() -> None: ...

def hook(action: str) -> Wrapped: ...
def add_hook(action: str, hook: Callable[NextType, dict[str, Any]]) -> None: ...
def safe_open(path: str) -> str: ...
def jput(char: str) -> None: ...
def jprint(string: str) -> None: ...
def load_hook_from_file(path: str) -> None: ...
def add_metadata(metadata: dict[str, str]) -> None: ...
